import { 
  User, 
  Mail, 
  Link, 
  Instagram, 
  Twitter, 
  Youtube, 
  Github,
  Facebook,
  Music,
  MessageCircle, 
  CreditCard,
  Gamepad2,
  Coffee,
  Heart,
  DollarSign,
  Play,
  Camera,
  Headphones,
} from 'lucide-react'

// Import official brand icons from React Icons (Simple Icons & FontAwesome)
import { 
  SiTiktok, 
  SiTwitch, 
  SiDiscord, 
  SiSpotify, 
  SiSnapchat, 
  SiTelegram, 
  SiSoundcloud, 
  SiPaypal, 
  SiPatreon, 
  SiKofi, 
  SiBuymeacoffee, 
  SiOnlyfans, 
  SiSteam, 
  SiKick, 
  SiReddit, 
  SiPinterest,
  SiLastdotfm,
  SiCashapp,
  SiRoblox,
  SiGitlab,
  SiX 
} from 'react-icons/si'

export const iconMap = {
  // Generic
  Link,
  Mail,
  User,
  Music,
  MessageCircle,
  CreditCard,
  Gamepad2,
  Coffee,
  Heart,
  DollarSign,
  Play,
  Camera,
  Headphones,

  // Socials (Lucide)
  Instagram,
  Youtube,
  Github,
  Facebook,

  // Socials (Official Brands)
  Twitter, // Keep Lucide Twitter bird as fallback or alternative
  X: SiX,
  Tiktok: SiTiktok,
  Twitch: SiTwitch,
  Discord: SiDiscord,
  Spotify: SiSpotify,
  Snapchat: SiSnapchat,
  Telegram: SiTelegram,
  Soundcloud: SiSoundcloud,
  Paypal: SiPaypal,
  Patreon: SiPatreon,
  Kofi: SiKofi,
  Buymecoffee: SiBuymeacoffee,
  Onlyfans: SiOnlyfans,
  Steam: SiSteam,
  Kick: SiKick,
  Reddit: SiReddit,
  Pinterest: SiPinterest,
  Lastfm: SiLastdotfm,
  Cashapp: SiCashapp,
  Roblox: SiRoblox,
  Gitlab: SiGitlab
}
