export const socialPlatforms = [
  { value: 'Link', label: 'Generic Link', icon: 'Link', color: '#6366f1' },
  { value: 'Instagram', label: 'Instagram', icon: 'Instagram', color: '#E4405F' },
  { value: 'Twitter', label: 'Twitter', icon: 'Twitter', color: '#1DA1F2' },
  { value: 'X', label: 'X (Twitter)', icon: 'X', color: '#000000' },
  { value: 'Youtube', label: 'YouTube', icon: 'Youtube', color: '#FF0000' },
  { value: 'Github', label: 'GitHub', icon: 'Github', color: '#333' },
  { value: 'Mail', label: 'Email', icon: 'Mail', color: '#EA4335' },
  { value: 'Twitch', label: 'Twitch', icon: 'Twitch', color: '#9146FF' },
  { value: 'Facebook', label: 'Facebook', icon: 'Facebook', color: '#1877F2' },
  { value: 'TikTok', label: 'TikTok', icon: 'Tiktok', color: '#000000' },
  { value: 'OnlyFans', label: 'OnlyFans', icon: 'Onlyfans', color: '#00AFF0' },
  { value: 'Spotify', label: 'Spotify', icon: 'Spotify', color: '#1DB954' },
  { value: 'Snapchat', label: 'Snapchat', icon: 'Snapchat', color: '#FFFC00' },
  { value: 'Telegram', label: 'Telegram', icon: 'Telegram', color: '#0088CC' },
  { value: 'SoundCloud', label: 'SoundCloud', icon: 'Soundcloud', color: '#FF5500' },
  { value: 'PayPal', label: 'PayPal', icon: 'Paypal', color: '#00457C' },
  { value: 'Roblox', label: 'Roblox', icon: 'Roblox', color: '#00A2FF' },
  { value: 'CashApp', label: 'CashApp', icon: 'Cashapp', color: '#00D632' },
  { value: 'GitLab', label: 'GitLab', icon: 'Gitlab', color: '#FC6D26' },
  { value: 'Reddit', label: 'Reddit', icon: 'Reddit', color: '#FF4500' },
  { value: 'Steam', label: 'Steam', icon: 'Steam', color: '#171A21' },
  { value: 'Kick', label: 'Kick', icon: 'Kick', color: '#53FC18' },
  { value: 'Pinterest', label: 'Pinterest', icon: 'Pinterest', color: '#BD081C' },
  { value: 'LastFM', label: 'Last.fm', icon: 'Lastfm', color: '#D51007' },
  { value: 'BuyMeACoffee', label: 'Buy Me a Coffee', icon: 'Buymecoffee', color: '#FFDD00' },
  { value: 'Kofi', label: 'Ko-fi', icon: 'Kofi', color: '#FF5E5B' },
  { value: 'Patreon', label: 'Patreon', icon: 'Patreon', color: '#FF424D' },
  { value: 'Discord', label: 'Discord', icon: 'Discord', color: '#5865f2'}
]
