export const socialPlatforms = [
  { value: 'Link', label: 'Generic Link', icon: 'Link', color: '#6366f1' },
  { value: 'Instagram', label: 'Instagram', icon: 'Instagram', color: '#E4405F' },
  { value: 'Twitter', label: 'Twitter/X', icon: 'Twitter', color: '#1DA1F2' },
  { value: 'Youtube', label: 'YouTube', icon: 'Youtube', color: '#FF0000' },
  { value: 'Github', label: 'GitHub', icon: 'Github', color: '#333' },
  { value: 'Mail', label: 'Email', icon: 'Mail', color: '#EA4335' },
  { value: 'Twitch', label: 'Twitch', icon: 'Twitch', color: '#9146FF' },
  { value: 'Facebook', label: 'Facebook', icon: 'Facebook', color: '#1877F2' },
  { value: 'TikTok', label: 'TikTok', icon: 'Play', color: '#000000' },
  { value: 'OnlyFans', label: 'OnlyFans', icon: 'Heart', color: '#00AFF0' },
  { value: 'Spotify', label: 'Spotify', icon: 'Music', color: '#1DB954' },
  { value: 'Snapchat', label: 'Snapchat', icon: 'Camera', color: '#FFFC00' },
  { value: 'Telegram', label: 'Telegram', icon: 'MessageCircle', color: '#0088CC' },
  { value: 'SoundCloud', label: 'SoundCloud', icon: 'Headphones', color: '#FF5500' },
  { value: 'PayPal', label: 'PayPal', icon: 'CreditCard', color: '#00457C' },
  { value: 'Roblox', label: 'Roblox', icon: 'Gamepad2', color: '#00A2FF' },
  { value: 'CashApp', label: 'CashApp', icon: 'DollarSign', color: '#00D632' },
  { value: 'GitLab', label: 'GitLab', icon: 'Github', color: '#FC6D26' },
  { value: 'Reddit', label: 'Reddit', icon: 'MessageCircle', color: '#FF4500' },
  { value: 'Steam', label: 'Steam', icon: 'Gamepad2', color: '#171A21' },
  { value: 'Kick', label: 'Kick', icon: 'Play', color: '#53FC18' },
  { value: 'Pinterest', label: 'Pinterest', icon: 'Camera', color: '#BD081C' },
  { value: 'LastFM', label: 'Last.fm', icon: 'Headphones', color: '#D51007' },
  { value: 'BuyMeACoffee', label: 'Buy Me a Coffee', icon: 'Coffee', color: '#FFDD00' },
  { value: 'Kofi', label: 'Ko-fi', icon: 'Heart', color: '#FF5E5B' },
  { value: 'Patreon', label: 'Patreon', icon: 'DollarSign', color: '#FF424D' },
  { value: 'Discord', label: 'Discord', icon: 'MessageCircle', color: '#5865f2'}
]
